/**
 * ROUTE — leads.js
 * POST /v1/restaurants/:slug/leads
 *
 * Receives catering enquiry form submissions.
 * Replaces the localStorage write + WhatsApp deep-link in V7 behaviour.js.
 * The WhatsApp deep-link is still generated by the frontend (non-breaking),
 * but the lead is now persisted in Postgres as the primary store.
 */

'use strict';

const express  = require('express');
const { z }    = require('zod');
const leadService = require('../../services/lead.service');

const router = express.Router();

const CreateLeadSchema = z.object({
  name:       z.string().min(1).max(120),
  company:    z.string().min(1).max(150),
  email:      z.string().email().max(120),
  phone:      z.string().min(10).max(20),
  budget:     z.string().max(30).optional(),
  headcount:  z.string().max(20).optional(),
  event_type: z.string().max(50).optional(),
  date_start: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
  date_end:   z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
  notes:      z.string().max(2000).optional(),
});

router.post('/', async (req, res, next) => {
  try {
    const parsed = CreateLeadSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ error: 'Invalid request', details: parsed.error.flatten() });
    }

    const result = await leadService.createLead(req.tenant, parsed.data);

    // Return ref + tier so the frontend confirmation screen still works
    res.status(201).json({
      ok:   true,
      ref:  result.ref,
      tier: result.tier,
    });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
